### ISSUE TITLE
UserAccounts instead of AccountsEntry

### ISSUE THREAD

**Issue by kevohagan** [yogiben/meteor-starter#32]
would you guys consider using @splendido's amazing useraccounts suite of packages instead of AccountsEntry. I think it is more maintained.

I wouldnt mind helping out with a PR.

https://github.com/meteor-useraccounts

**Comment by yogiben** [comment]
Currently, there's nothing wrong with account-entry and lots of other stuff to fix.

Could you summarise why this would be a good move for starter?

**Comment by kevohagan** [comment]
Accounts Entry has not been that actively maintained over the past few months, whereas User Accounts is very much so. Plus see this thread from josh owens

https://github.com/Differential/accounts-entry/issues/326#issuecomment-65813192

' will be announcing this project is being deprecated in favor of UserAccounts (formely AccountTemplates) projects moving forward.'

also using User Accounts will be a more versatile option for the future ( if one day meteor admin decides to abstract bootstrap from the package)

also in User Accounts its very easy to do a redirect for the /admin route to /login when the user is not logged in yet for example.

**Comment by kevohagan** [comment]
This is just a suggestion for the future!

as you say, there is probably no need to do it now ( even if i would gladly do a PR , if you guys are interested ).

I just wanted to raise the subject and see if it was of interest or now.

Awesome package btw @yogiben and @mpowaga !! Im loving it!

**Comment by kevohagan** [comment]
and btw as you know, telescope changed from accounts entry to user accounts a while back ;)

**Comment by KrishnaPG** [comment]
Is the issue https://github.com/yogiben/meteor-starter/issues/34 anyway related? 

If moving to user accounts can resolve the login redirect problems, perhaps it should be considered.

**Comment by splendido** [comment]
@KrishnaPG, redirects are one of the selling points for useraccounts ;-)

...you can try it on one of the live examples linked from [useraccounts.meteor.com](https://useraccounts.meteor.com)

Luca

**Comment by splendido** [comment]
:+1:
