### ISSUE TITLE
Should go to original URL after login

### ISSUE THREAD

**Issue by KrishnaPG** [yogiben/meteor-starter#34]
After login, it is always going to /dashboard and not to the original request.

For example, if originally a request was made to another page, say `/admin` or `/profile` (or any other page), it prompts for sign-in, which is correct. But, after signin, it goes to `/dashboard` and not to `/admin` or `/profile` as requested.

**Comment by yogiben** [comment]
I agree. Maybe the path can be stored as a session variable.

**Comment by mpowaga** [comment]
accounts-entry is supposed to have this feature but has a bug.
