### ISSUE TITLE
Default Admin Account

### ISSUE THREAD

**Issue by matteodem** [yogiben/meteor-starter#36]
Cool admin package, I would like to test it online with this starter. Any way to get the credentials for the default admin that is configured? Having them in the README.md would be even better

**Comment by yogiben** [comment]
The readme for admin is foudn here: https://github.com/yogiben/meteor-admin

The first user is made admin when they go to `/admin`

**Comment by matteodem** [comment]
I mean this URL http://starter.meteor.com/. Btw the link in this README is wrongly linked.

**Comment by yogiben** [comment]
Link is fixed.

Added default login to readme.

**Comment by matteodem** [comment]
thank you
