### ISSUE TITLE
Social Media Links Do not appear in Footer.

### ISSUE THREAD

**Issue by theroadrunnershow** [yogiben/meteor-starter#51]
The social media links in the footer are not appearing? Not sure why? 

                <div class="col-md-offset-2 col-md-8">
                    <ul class="social-networks">
                        {{#each socialMedia}}
                        <li><a href="{{url}}" target="_blank">
                        <span class="fa-stack fa-2x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-{{icon}} fa-stack-1x fa-inverse"></i>
                        </span></a>
                        </li>
                        {{/each}}
                    </ul>
                </div>

**Comment by KrishnaPG** [comment]
What was the solution for this?

Downloaded the code today and with fresh build, getting the below (just blue circles with no font icons)

![image](https://cloud.githubusercontent.com/assets/4610831/8828203/95b4a8ec-30ae-11e5-9387-b14385ea314f.png)

**Comment by KrishnaPG** [comment]
For some reason, this commit https://github.com/yogiben/meteor-starter/commit/803b07a44d026de7cca45998fe21d17f6bd737fa rolled back the changes made by this one https://github.com/yogiben/meteor-starter/commit/e2e210ea68aa9f1f21b7097a3ae95ecf35ca70c1 causing this problem.

The file `both/config/_config.coffee` need to be corrected to get back that code from https://github.com/yogiben/meteor-starter/commit/e2e210ea68aa9f1f21b7097a3ae95ecf35ca70c1 where @yogiben had it correct with social icons
