### ISSUE TITLE
Images of new user

### ISSUE THREAD

**Issue by yogiben** [yogiben/meteor-starter#58]
`/server/accounts.coffee`

1. Test that Facebook, Google and Twitter sign in works
2. Test that the profile images are correctly grabbed from above

3. Check that Gravatar image is correctly pulled
4. Handle when there is no gravatar image

Currently, the Gravatar image is stored as an URL. It should be stored as an image.

![image](https://cloud.githubusercontent.com/assets/1703155/7411672/13e9b1da-ef32-11e4-9052-760a8b923ad2.png)

When there is no gravatar for that email, the profile picture should be blank

**Comment by yogiben** [comment]
Don't commit subprojects. It's always a mess.

**Comment by snamoah** [comment]
@yogiben are you referring to the meteor-autoform-file package?
