### ISSUE TITLE
Just installed, get this on startup...

### ISSUE THREAD

**Issue by ssteinerx** [yogiben/meteor-starter#68]
Didn't see mention of dependency?

=> Started proxy.
=> Started MongoDB.
W20150518-10:36:05.381(-4)? (STDERR) WARNING:
W20150518-10:36:05.382(-4)? (STDERR) cfs:graphicsmagick could not find "graphicsMagic" or "imageMagic" on the
W20150518-10:36:05.382(-4)? (STDERR) system.
W20150518-10:36:05.382(-4)? (STDERR)
W20150518-10:36:05.382(-4)? (STDERR) I just checked PATH to see if I could find the GraphicsMagick or ImageMagic
W20150518-10:36:05.382(-4)? (STDERR) unix/mac os/windows binaries on your system, I failed.
W20150518-10:36:05.382(-4)? (STDERR)
W20150518-10:36:05.382(-4)? (STDERR) Why:
W20150518-10:36:05.382(-4)? (STDERR) 1. I may be blind or naive, help making me smarter
W20150518-10:36:05.382(-4)? (STDERR) 2. You havent added the path to the binaries
W20150518-10:36:05.382(-4)? (STDERR) 3. You havent actually installed GraphicsMagick or ImageMagick
W20150518-10:36:05.383(-4)? (STDERR)
W20150518-10:36:05.383(-4)? (STDERR) *** Make sure "$PATH" environment is configured "PATH:/path/to/binaries" ***
W20150518-10:36:05.383(-4)? (STDERR)
W20150518-10:36:05.383(-4)? (STDERR) Installation hints:
W20150518-10:36:05.383(-4)? (STDERR) * Mac OS X "brew install graphicsmagick" or "brew install imagemagick"
W20150518-10:36:05.383(-4)? (STDERR) * Linux download rpm or use packagemanager
W20150518-10:36:05.383(-4)? (STDERR) * Centos "yum install GraphicsMagick"* Windows download the installer and run
I20150518-10:36:06.950(-4)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
=> Started your app.

=> App running at: http://localhost:3000/

**Comment by femiveys** [comment]
You havent actually installed GraphicsMagick or ImageMagick

**Comment by ssteinerx** [comment]
Yes, I figured that out.  I don't recall that it was in the build instructions as a requirement.  I just used homebrew and it's now fine.

**Comment by abtx** [comment]
I gave the same issue. Both packages are in meteor packages, and installing them via homebrew doesn't seem to help. Any ideas why would this happen?

**Comment by abtx** [comment]
Nevermind, it was a brew issue.
