### ISSUE TITLE
Image upload has no effect

### ISSUE THREAD

**Issue by reduxdj** [yogiben/meteor-starter#82]
I have the binaries included, but when I go to upload to the admin panel nothing happens?

**Comment by reduxdj** [comment]
The provided value 'undefined' is not a valid enum value of interface XMLHttpRequestResponseType.

line 101 of httpCall

  xhr.responseType = options.responseType;

there is no responseType on options (this probably has nothing to do with your library)

**Comment by kertal** [comment]
same problem here

**Comment by reduxdj** [comment]
Still not working....

**Comment by reduxdj** [comment]
mm: this works (didn't get the latest version when I did a meteor remove then add, had to explicitly define in packages.
yogiben:admin@1.2.1
yogiben:pretty-email
yogiben:autoform-file
yogiben:autoform-map
yogiben:helpers
