### ISSUE TITLE
Meteor-starter 1.2.1 here.

### ISSUE THREAD

**Issue by mondrus** [yogiben/meteor-starter#94]
Test and give me issues and push requests. I'll try to do my best to stay on top of this package as long as I can. Thanks to YogiBen and CaptainN for their work. SOG (shoulders of giants)

https://github.com/mondrus/meteor-starter

**Comment by chauhang** [comment]
Getting following errors on running meteor update for ver 1.2.1

=> Errors while upgrading packages:

While selecting package versions:
error: Conflict: Constraint less@1.0.14 is not satisfied by less
2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@1.0.0 || 2.5.0 <- yogiben:autoform-file 0.3.0
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.14 <- bootstrap 0.3.1
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@1.0.8 <- user-thumbs 0.0.8
* less@1.0.11 <- comments 0.1.0
* less@1.0.11 <- favorites 0.0.4
* less@1.0.11 <- notifications 0.0.7
* less@1.0.0 || 2.5.0 <- yogiben:admin 1.2.3

Conflict: Constraint less@1.0.8 is not satisfied by less 2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@1.0.0 || 2.5.0 <- yogiben:autoform-file 0.3.0
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.14 <- bootstrap 0.3.1
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@1.0.8 <- user-thumbs 0.0.8
* less@1.0.11 <- comments 0.1.0
* less@1.0.11 <- favorites 0.0.4
* less@1.0.11 <- notifications 0.0.7
* less@1.0.0 || 2.5.0 <- yogiben:admin 1.2.3

Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@1.0.0 || 2.5.0 <- yogiben:autoform-file 0.3.0
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.14 <- bootstrap 0.3.1
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@1.0.8 <- user-thumbs 0.0.8
* less@1.0.11 <- comments 0.1.0
* less@1.0.11 <- favorites 0.0.4
* less@1.0.11 <- notifications 0.0.7
* less@1.0.0 || 2.5.0 <- yogiben:admin 1.2.3

**Comment by mondrus** [comment]
Try deleting your cache. I’m not getting those errors anymore.

 

Thanks

 

David Mondrus

O: 718-360-5438

C: 917-912-5110

Skype: David.Mondrus

**Comment by chauhang** [comment]
I tried all combinations still no luck, continue to get the conflict errors. I cleared the browser cache and also deleted the .meteor/local. Also tried creating a brand new meteor project and then copying the meteor-admin and meteor-starter as you described on your fork page (https://github.com/mondrus/meteor-starter/blob/master/README.md) . Things work with Meteor 1.1.0.2 but not with ver 1.2.1.  

Could you also please confirm what is the release number listed in your .meteor/release file and also the latest contents of your .meteor/versions files.

I tested on Windows 10 and Ubuntu LTS 14_04 with brand new Meteor 1.2.1 install and getting same errors on both platforms.

**Comment by mondrus** [comment]
Not sure what the issue is. Where are you downloading from?

 

I’m showing Meteor – version is 1.2.1

 

 

 

 

 

 

Thanks

 

David Mondrus

O: 718-360-5438

C: 917-912-5110

Skype: David.Mondrus

**Comment by chauhang** [comment]
I tried from the master branch of both yogiben/meteor-starter and mondrus/meteor-starter. Both are showing 5 to 7 months old files in the .meteor folder with meteor version 1.1.0.2 in the .meteor/release file. On updating the project to Meteor 1.2.1 it gives the errors listed on this thread.

Please let me know if I am missing something. Thanks for your help in advance.

**Comment by chauhang** [comment]
I was able to narrow down the issues by manually adding each of the packages using "meteor add <package>". Packages causing problems are: bootstrap, comments, notifications, yogiben:admin, zimme:iron-router-active, yogiben:autoform-file

Here are the actual errors:

PS C:\ard\experiment\m-starter> meteor add bootstrap
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint less@1.0.14 is not satisfied by less
2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@1.0.0 || 2.5.0 <- yogiben:autoform-file 0.3.0
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.14 <- bootstrap 0.3.1

PS C:\ard\experiment\m-starter> meteor add user-thumbs
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint less@1.0.8 is not satisfied by less
2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@1.0.0 || 2.5.0 <- yogiben:autoform-file 0.3.0
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.8 <- user-thumbs 0.0.8

PS C:\ard\experiment\m-starter> meteor add comments
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less
2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@1.0.0 || 2.5.0 <- yogiben:autoform-file 0.3.0
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.11 <- comments 0.1.0

PS C:\ard\experiment\m-starter> meteor add favorites
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less
2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@1.0.0 || 2.5.0 <- yogiben:autoform-file 0.3.0
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.11 <- favorites 0.0.4

PS C:\ard\experiment\m-starter> meteor add notifications
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less
2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@1.0.0 || 2.5.0 <- yogiben:autoform-file 0.3.0
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.11 <- notifications 0.0.7

PS C:\ard\experiment\m-starter> meteor add yogiben:admin
 => Errors while adding packages:

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: aldeed:template-extension 3.4.3, was 4.0.0. Constraints on package "aldeed:template-extension":
* aldeed:template-extension@3.4.3 <- yogiben:admin 1.2.3

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

PS C:\ard\experiment\m-starter> meteor add zimme:iron-router-active
Changes to your project's package version selections:

zimme:active-route        added, version 2.0.4_1
zimme:iron-router-active  added, version 2.0.1

zimme:iron-router-active: Deprecated! Use zimme:active-route

PS C:\ard\experiment\m-starter> meteor update
This project is already at Meteor 1.2.1, the latest release.
Your top-level dependencies are at their latest compatible versions.

The following top-level dependencies were not updated to the very latest version available:
 * yogiben:autoform-file 0.3.0 (1.0.1 is available)
 
 PS C:\ard\experiment\m-starter> meteor list
accounts-base                    1.2.2  A user account system
accounts-facebook                1.0.6  Login service for Faceboo...
accounts-google                  1.0.6  Login service for Google ...
accounts-password                1.1.4  Password support for acco...
accounts-twitter                 1.0.6  Login service for Twitter...
accounts-ui                      1.1.6  Simple templates to add l...
alanning:roles                   1.2.14  Authorization package fo...
aldeed:autoform                  5.7.1  Easily create forms with ...
aldeed:collection2               2.5.0  Automatic validation of i...
aldeed:simple-schema             1.4.0  A simple schema validatio...
aldeed:template-extension        4.0.0  Adds template features cu...
blaze-html-templates             1.0.1  Compile HTML templates in...
cfs:graphicsmagick               0.0.18  Adds `gm` to scope with ...
cfs:gridfs                       0.0.33  GridFS storage adapter f...
cfs:standard-packages            0.5.9  Filesystem for Meteor, co...
coffeescript                     1.0.11  Javascript dialect with ...
dburles:collection-helpers       1.0.4  Transform your collection...
deps                             1.0.9  Deprecated: Use the 'trac...
fastclick                        1.0.7  Faster touch events on mo...
fortawesome:fontawesome          4.4.0_1  Font Awesome (official)...
iron:router                      1.0.12  Routing specifically des...
jparker:gravatar                 0.4.1  Simple package to use gra...
juliancwirko:s-alert             3.1.2  Simple and fancy notifica...
juliancwirko:s-alert-stackslide  3.1.2  StackSlide effect for s-a...
less                             2.5.1  Leaner CSS language
manuelschoebel:ms-seo            0.4.1  Easily config SEO for you...
meteor-base                      1.0.1  Packages that every Meteo...
meteorhacks:subs-manager         1.6.2  Subscriptions Manager for...
momentjs:moment                  2.10.6  Moment.js (official): pa...
mongo                            1.1.3  Adaptor for using MongoDB...
multiply:iron-router-progress    1.0.2  Progressbar for iron:router
natestrauser:animate-css         3.4.0  Animate.css packaged for ...
percolate:momentum               0.7.2  Reactive animations
percolate:momentum-iron-router   0.7.0  A momentum plugin for tra...
raix:handlebar-helpers           0.2.5  Handlebar helpers
random                           1.0.5  Random number generator a...
reywood:publish-composite        1.4.2  Publish a set of related ...
service-configuration            1.0.5  Manage the configuration ...
session                          1.1.1  Session variable
spiderable                       1.0.9  Makes the application cra...
standard-minifiers               1.0.2  Standard minifiers used w...
timmyg:wow                       1.0.1  WOW css animations
tracker                          1.0.9  Dependency tracker to all...
tsega:skrollr                    0.0.2  A meteor package for the ...
useraccounts:bootstrap           1.12.4  Accounts Templates style...
utilities:avatar                 0.9.2  Consolidated user avatar ...
yogiben:autoform-file            0.3.0* File upload for AutoForm
yogiben:autoform-map             0.2.0  Edit location coordinates...
yogiben:autoform-modals          0.3.8  Create, update and delete...
yogiben:helpers                  0.0.6  Meteor helpers that shoul...
yogiben:mixpanel                 0.0.7  MixPanel on client and se...
yogiben:pretty-email             0.0.7  Send pretty emails
zimme:active-route               2.3.2  Active route helpers


* New versions of these packages are available! Run 'meteor update'   to try to update those packages to their latest versions. If your   packages cannot be updated further, try typing   `meteor add <package>@<newVersion>` to see more information.
  
 PS C:\ard\experiment\m-starter> meteor add yogiben:autoform-file@1.0.1
 => Errors while adding packages:

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.1.
Constraints on package "less":
* less@=2.5.1 <- top level
* less@2.5.0_1 <- accounts-ui 1.1.6
* less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
* less@2.5.0_2 <- yogiben:autoform-modals 0.3.8
* less@2.5.0_1 <- multiply:iron-router-progress 1.0.2
* less@1.0.11 <- yogiben:autoform-file 1.0.1

Conflict: Constraint aldeed:autoform@4.0.2 is not satisfied by aldeed:autoform 5.7.1.
Constraints on package "aldeed:autoform":
* aldeed:autoform@5.5.1 <- yogiben:autoform-modals 0.3.8
* aldeed:autoform@5.6.0 <- yogiben:autoform-map 0.2.0
* aldeed:autoform@4.0.2 <- yogiben:autoform-file 1.0.1

**Comment by mondrus** [comment]
Did you get the latest branch from Mondrus/meteor-start ? It’s giving me 1.2.1 here…

 

Thanks

 

David Mondrus

O: 718-360-5438

C: 917-912-5110

Skype: David.Mondrus

**Comment by chauhang** [comment]
Did you checkin all the files? Only changes in the Master branch for last commit are to the Readme.md file. Here is what I am seeing: 

![git](https://cloud.githubusercontent.com/assets/4461127/11509798/14d621f0-9815-11e5-87ec-534c871ad81a.PNG)

**Comment by mondrus** [comment]
I think you have a caching problem:

![image](https://cloud.githubusercontent.com/assets/6376607/11560707/65c7e32e-9990-11e5-8e97-b3224c8e7584.png)

**Comment by mondrus** [comment]
Ok, just uploaded a new version, try this one

**Comment by chauhang** [comment]
Making progress....

Getting error for the user-preferences package. Could not find it on Atmosphere. Tried removing from list but did not help as it is a pre-req for comments package.  Let me know where to add this package from.

**Comment by mondrus** [comment]
Did you try grabbing the latest repo?


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by chauhang** [comment]
Yes this was with the new version you uploaded today. Looks like you forgot to checkin the files under the packages/user-preferences folder -- it is empty on github

**Comment by mondrus** [comment]
I don't have a packages/user-preference folder at all.... Hmm....

**Comment by chauhang** [comment]
I meant the user-helpers package. The folder is empty on your github. 
![uh-2](https://cloud.githubusercontent.com/assets/4461127/11629499/33e36a6e-9cbe-11e5-875a-fd11f2d780d5.PNG)

![uh](https://cloud.githubusercontent.com/assets/4461127/11629502/382ff5b0-9cbe-11e5-98c2-d88aaeee7709.PNG)

If you do a sanity check by getting all the files from git hub after checking them and doing a complete build in a brand new folder / another machine or inside a new docker container, should be able to reproduce at your end.

**Comment by mondrus** [comment]
Did that, that’s where the new version came from…

 

Thanks

 

David Mondrus

O: 718-360-5438

C: 917-912-5110

Skype: David.Mondrus

**Comment by mondrus** [comment]
Ok, new version up. I have working on my machine image uploads and login/register. There are still issues outstanding so feel free to help out.

**Comment by chauhang** [comment]
Still same problem. Files are missing from github. Folders packages/user-helpers and packages/autoform-file are empty (see below)

![image](https://cloud.githubusercontent.com/assets/4461127/11693765/938f54ca-9e5b-11e5-8233-e4ce7041650a.png)

**Comment by mondrus** [comment]
Ok, that's resolved too. (BTW, they were in that zip file I uploaded as well)

**Comment by chauhang** [comment]
Thanks :) Things are working now with Meteor 1.2.1

**Comment by mondrus** [comment]
Ok, changing this to a pull request and closing issue.
