### ISSUE TITLE
Picture upload not working

### ISSUE THREAD

**Issue by fdddk23** [yogiben/meteor-starter#97]
Hi,

When I upload a picture via yogiben:autform-file it (seems to be) uploaded to my cfs collection but afterwards it is shown as an broken link and following error message appears in the console:

http-call-client.js:101 The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.

The broken link has following html: img alt="" class="img-fileUpload-thumbnail img-thumbnail img-rounded" src="/cfs/files/Attachments/9q38FobbxRknLxo7p/pic05.jpg?token=eyJhdXRoVG9rZW4iOiJ0RGdYbHdkcnREdmJEOHdVTG1sUkY2Z1dybDlzZmkzM2FRMThnU1JaSkM1In0%3D"

**Comment by mondrus** [comment]
Are you running Windows or Unix?

 

Thanks

**Comment by fdddk23** [comment]
Windows

**Comment by mondrus** [comment]
See previous commits. You MUST HAVE gm.exe working from the command line. It’s a windows utility to manipulate images. Graphics Magic is the package.  http://www.graphicsmagick.org/

 

 

 

Thanks

 

David Mondrus

**Comment by fdddk23** [comment]
Thank you for your help!
I didn't knew that. I installed now gm and it is also available from command line. Nevertheless the same problem :/
What else can I try?

**Comment by fdddk23** [comment]
Nobody else experiencing a problem with this plugin?

**Comment by snamoah** [comment]
@fdddk23 do you have the still autopublish package in your app?

**Comment by fdddk23** [comment]
No, I havent' autopublish in my app

**Comment by snamoah** [comment]
@fdddk23 you would have to then publish and subscribe to the picture collection in the template your rendering the image in

**Comment by fdddk23** [comment]
i.e. at Profile this is done:

  this.route("profile", {
    path: "/profile",
    waitOn: function() {
      return Meteor.subscribe('profilePictures');
    }
  });

Meteor.publish('profilePictures', function() {
  return ProfilePictures.find();
});

So this should be ok?!

**Comment by fdddk23** [comment]
Ohhh suddenly it is now working :) I didn't change anything... maybe due to a restart after installing GM ?!
I will try now but thanks to all :)

**Comment by snamoah** [comment]
Cool!
